# framework default service
x-sail-svc: &sail-svc
  build:
    context: vendor/laravel/sail/runtimes/8.2
    dockerfile: Dockerfile
    args:
      WWWGROUP: '${WWWGROUP}'
  image: sail-8.2/app
  extra_hosts:
    - 'host.docker.internal:host-gateway'
  environment:
    WWWUSER: '${WWWUSER}'
    LARAVEL_SAIL: 1
    XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
    XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
  volumes:
    - '.:/var/www/html'

# production service
x-unit-svc: &unit-svc
  image: cyrille/backend
  build:
    dockerfile: build/api/Dockerfile
    context: .
    target: api
  env_file:
    - .env
  volumes:
    - '.:/app'

services:
  init:
    <<: *sail-svc
    command: php artisan migrate:fresh --seed
    networks:
      - sail
    depends_on:
      pgsql:
        condition: service_healthy
  laravel.test:
    <<: *sail-svc
    ports:
      - '${APP_PORT:-80}:80'
    networks:
      - sail
    depends_on:
      - init
  worker:
    <<: *sail-svc
    command: php artisan queue:work
    networks:
      - sail
    depends_on:
      - laravel.test
  pgsql:
    image: 'postgres:15'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'sail-pgsql:/var/lib/postgresql/data'
      - './build/postgres/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
    networks:
      - sail
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-q', '-d', '${DB_DATABASE}', '-U', '${DB_USERNAME}' ]
      retries: 3
      timeout: 5s
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      retries: 3
      timeout: 5s

networks:
  sail:
    driver: bridge

volumes:
  sail-pgsql:
    driver: local
  sail-redis:
    driver: local
