apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: robonen/cyrille-backend:latest
    newTag: v1.1.0
  - name: postgres
    newTag: '15'
  - name: redis
    newTag: '6.2.13'

namespace: cyrille

resources:
  - 'namespace.yaml'
  - 'secret.yaml'
  - 'configmap.yaml'
  - 'database-deployment.yaml'
  - 'cache-deployment.yaml'
  - 'app-deployment.yaml'
  - 'database-service.yaml'
  - 'cache-service.yaml'
  - 'app-service.yaml'
