apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: robonen/cyrille-backend:latest
    newTag: latest
  - name: postgres
    newTag: '15'

namespace: cyrille

resources:
  - 'namespace.yaml'
  - 'secret.yaml'
  - 'configmap.yaml'
  - 'database-deployment.yaml'
  - 'app-deployment.yaml'
  - 'database-service.yaml'
  - 'app-service.yaml'
