apiVersion: v1
kind: Secret
metadata:
  name: app-secret
stringData:
  APP_KEY: 'base64:S5dc/vRiF7cBLIx5XzxtDqih5iZ82EXnYCUSSH7eXwA='
  DB_USERNAME: 'ViSm0EpDnR'
  DB_PASSWORD: 'XzxtDqih5iZ82E'
  JWT_SECRET: 'mSDWoIoGF4WViSm0EpDnRuw1CMezuEUax9bxTlZksSZYrR0YNdDQ9XUpLKdzsK3M'

---

apiVersion: v1
kind: Secret
metadata:
  name: database-secret
stringData:
  POSTGRES_USER: 'ViSm0EpDnR'
  POSTGRES_PASSWORD: 'XzxtDqih5iZ82E'
