apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cyrille-ceritifcate
spec:
  dnsNames:
    - api.cyrille.ru
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: cyrille-certificate
