apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-robonen-ceritifcate
spec:
  dnsNames:
    - robonen.dacdevops.ru
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: robonen-certificate
