apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: robonen/cyrille-backend:latest
    newTag: latest
  - name: postgres
    newTag: '15'

namespace: cyrille

resources:
  - '../../base'
  - 'ingress.yaml'
  - 'certificate.yaml'
